apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    app.kubernetes.io/name: catalogue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app.kubernetes.io/name: cart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app.kubernetes.io/name: user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    app.kubernetes.io/name: shipping
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app.kubernetes.io/name: payment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
