apiVersion: v1
kind: Pod
metadata:
  name: "{{.Values.component}}-pod"
  labels:
    app.kubernetes.io/name: {{.Values.component}}
spec:
  containers:
    - name: "{{.Values.component}}-container"
      image: 060795929502.dkr.ecr.us-east-1.amazonaws.com/{{.Values.component}}:{{.Values.App_Version}}
      ports:
        - containerPort: {{.Values.appPort}}
  initContainers:
    - name: roboshop-init-cont
      image: 060795929502.dkr.ecr.us-east-1.amazonaws.com/project-init-cont:2.0.0
      imagePullPolicy: Always
