apiVersion: v1
kind: Pod
metadata:
  name: "{{.Values.component}}"
  labels:
    app.kubernetes.io/name: {{.Values.component}}
spec:
  volumes:
    - name: common
      emptyDir:
        sizeLimit: 5Mi
  serviceAccountName: {{ .Values.component }}
  containers:
    - name: "{{.Values.component}}"
      image: 060795929502.dkr.ecr.us-east-1.amazonaws.com/{{.Values.component}}:{{.Values.App_Version}}
      ports:
        - containerPort: {{.Values.appPort}}
      volumeMounts:
        - mountPath: /common
          name: common
  initContainers:
    - name: roboshop-init-cont
      image: 060795929502.dkr.ecr.us-east-1.amazonaws.com/project-init-cont:2.0.1
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /common
          name: common
      env:
        - name: PARAMETERS
          value: "{{.Values.PARAMETERS}}"