apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"  # Ensures SA is created first
    eks.amazonaws.com/role-arn: "arn:aws:iam::940482433230:role/EKS_PS_ACCESS_ROLE"
  name: {{.Values.component}}
